name: Scala CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  compile-and-test:

    runs-on: ubuntu-latest

    container: michelsteuwer/docker-scala-opencl:latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Compile
        run: sbt compile
      - name: Run tests
        run: sbt test
