name: Build and deploy documentation

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  pull_request:

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    container: michelsteuwer/docker-scala-opencl:scala2.12.10sbt1.3.5opencl2.0
    steps:
      - uses: actions/checkout@v2
        with:
          submodulues: recursive
      - name: Check documentation
        run: sbt docs/mdoc
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Build Documentation
        working-directory: docs-website
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build
